### ISSUE TITLE
Mongo restarting docker build error

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#35] opened 2023-11-08 18:58 UTC
**Describe the bug**
See https://discord.com/channels/1165866460745314304/1167801582923030538/1171861403615903784

**To Reproduce**
Docker build

**Additional context**

**Comment by krish240574** [comment] 2023-11-09 16:22
This occurs inside my VirtualBox VM, ubuntu 22.04 - I needed to have AVX enabled in my settings, the latest vesion of mongodb kept shutting down, for want of a processor that supported AVX. 
So I chose one of two options:
1. Enable AVX inside VirtualBox(haven't gotten around to researching and doing that, crazy day)
2. Use an older version of Mongo - I used 4.2 and I'm good to go, for now. 

Will update on the AVX settings.

**Comment by krish240574** [comment] 2023-11-09 16:23
I guess this is not a bug, just a one-off, maybe you could close this as "not a bug", @anada10 .

**Comment by anada10** [comment] 2023-11-09 19:18
Hi Kumar thanks for that added context and information, sure we will close
this as not a bug.

Regards,
Andrew

**Closed** 2023-11-09 19:19 UTC
